### ISSUE TITLE
r-ryantm is not compatible with nix-update updateScripts

### ISSUE THREAD

**Issue by ryantm** [ryantm/nixpkgs-update#227]
https://github.com/NixOS/nixpkgs/pull/94455#issuecomment-667556399

nixpkgs-update gets this error running as r-ryantm on a package that uses nix-update.
```
these derivations will be built:
  /nix/store/81x4psimcacgkmiqkaja0pi0gjf1alv5-packages.json.drv
these paths will be fetched (0.03 MiB download, 0.11 MiB unpacked):
  /nix/store/70zpgy8q9swkgc1vlvspcnln03455vvi-nix-prefetch-0.3.1
  /nix/store/a7r0r4vxchhdz3jr2hpib0g02a9s5pm3-nix-update-0.1
copying path '/nix/store/70zpgy8q9swkgc1vlvspcnln03455vvi-nix-prefetch-0.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/a7r0r4vxchhdz3jr2hpib0g02a9s5pm3-nix-update-0.1' from 'https://cache.nixos.org'...
building '/nix/store/81x4psimcacgkmiqkaja0pi0gjf1alv5-packages.json.drv'...
running post-build-hook '/nix/store/q56pid4rvlly41fn4q5hnmmd9860ylsf-post-build-hook.sh'...
/nix/store/19nj63a9kkf15nc2yq2cp3mdvzq4ixbh-stdenv-linux/setup: line 795: /tmp/env-vars: Permission denied

Going to be running update for following packages:
 - appeditor-1.1.0

Press Enter key to continue...
Running update for:
 - appeditor-1.1.0: UPDATING ...
 - appeditor-1.1.0: ERROR

--- SHOWING ERROR LOG FOR appeditor-1.1.0 ----------------------

error: Could not determine the runtime directory (i.e. XDG_RUNTIME_DIR).
$ nix eval --json (with import ./. {};
    let
      pkg = appeditor;
      position = if pkg ? isRubyGem then
        builtins.unsafeGetAttrPos "version" pkg
      else
        builtins.unsafeGetAttrPos "src" pkg;
    in {
      name = pkg.name;
      old_version = (builtins.parseDrvName pkg.name).version;
      filename = position.file;
      line = position.line;
      urls = pkg.src.urls or null;
      url = pkg.src.url or null;
      rev = pkg.src.url.rev or null;
      hash = pkg.src.outputHash;
      mod_sha256 = pkg.modSha256 or null;
      vendor_sha256 = pkg.vendorSha256 or null;
      cargo_sha256 = pkg.cargoSha256 or null;
    })
fetch https://github.com/donadigo/appeditor/releases.atom
Update 1.1.0 -> 1.1.1 in /var/cache/nixpkgs-update/nixpkgs/pkgs/applications/misc/appeditor/default.nix
$ nix-prefetch (import ./. {}).appeditor
Traceback (most recent call last):
  File "/nix/store/a7r0r4vxchhdz3jr2hpib0g02a9s5pm3-nix-update-0.1/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/a7r0r4vxchhdz3jr2hpib0g02a9s5pm3-nix-update-0.1/lib/python3.8/site-packages/nix_update/__init__.py", line 142, in main
    package = update(options)
  File "/nix/store/a7r0r4vxchhdz3jr2hpib0g02a9s5pm3-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 82, in update
    update_src_hash(opts, package.filename, package.hash)
  File "/nix/store/a7r0r4vxchhdz3jr2hpib0g02a9s5pm3-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 42, in update_src_hash
    target_hash = nix_prefetch([f"(import {opts.import_path} {{}}).{opts.attribute}"])
  File "/nix/store/a7r0r4vxchhdz3jr2hpib0g02a9s5pm3-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 37, in nix_prefetch
    res = run(["nix-prefetch"] + cmd)
  File "/nix/store/a7r0r4vxchhdz3jr2hpib0g02a9s5pm3-nix-update-0.1/lib/python3.8/site-packages/nix_update/utils.py", line 32, in run
    return subprocess.run(command, cwd=cwd, check=check, text=True, stdout=stdout)
  File "/nix/store/8hf2rpqx8fnx6a3jm9pvn0d40c065zxl-python3-3.8.3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-prefetch', '(import ./. {}).appeditor']' returned non-zero exit status 1.


--- SHOWING ERROR LOG FOR appeditor-1.1.0 ----------------------
```

I noticed the updateScript works fine when I run nixpkgs-update on my computer, so it is just a problem with the systemd environment used by r-ryantm.

cc @worldofpeace

**Comment by bhipple** [comment]
Perhaps try setting either `XDG_RUNTIME_DIR` or `HOME` in the systemd unit file?

**Comment by ryantm** [comment]
Should be fixed by https://github.com/nix-community/infra/commit/a7afa15ed4b0a94b2e3922b1e41cb19e85bde877

**Comment by ryantm** [comment]
With WoP's help revised fixes in https://github.com/nix-community/infra/commit/9f4ae2c2494232bfef3abdead17b5e373ac3c1e7
