### ISSUE TITLE
Obsidian failing to update

### ISSUE THREAD

**Issue by SamirHafez** [ryantm/nixpkgs-update#241]
From the logs:

```
2020-10-10T03:22:53 obsidian 0.9.1 -> 0.9.2 https://github.com/obsidianmd/obsidian-releases/releases
2020-10-10T03:23:03 [version] 
2020-10-10T03:23:03 [version] generic version rewriter does not support multiple hashes
2020-10-10T03:23:03 [rustCrateVersion] 
2020-10-10T03:23:03 [rustCrateVersion] No cargoSha256 found
2020-10-10T03:23:03 [golangModuleVersion] 
2020-10-10T03:23:03 [golangModuleVersion] Not a buildGoModule package with vendorSha256
2020-10-10T03:23:03 [updateScript] 
2020-10-10T03:23:09 FAIL [updateScript] Failed with exit code 1
/nix/store/333six1faw9bhccsx9qw5718k6b1wiq2-stdenv-linux/setup: line 796: /tmp/env-vars: Permission denied
```

Linked to https://github.com/ryantm/nixpkgs-update/issues/227

**Comment by ryantm** [comment]
```
2020-10-10T03:22:53 obsidian 0.9.1 -> 0.9.2 https://github.com/obsidianmd/obsidian-releases/releases
2020-10-10T03:23:03 [version] 
2020-10-10T03:23:03 [version] generic version rewriter does not support multiple hashes
2020-10-10T03:23:03 [rustCrateVersion] 
2020-10-10T03:23:03 [rustCrateVersion] No cargoSha256 found
2020-10-10T03:23:03 [golangModuleVersion] 
2020-10-10T03:23:03 [golangModuleVersion] Not a buildGoModule package with vendorSha256
2020-10-10T03:23:03 [updateScript] 
2020-10-10T03:23:09 FAIL [updateScript] Failed with exit code 1
/nix/store/333six1faw9bhccsx9qw5718k6b1wiq2-stdenv-linux/setup: line 796: /tmp/env-vars: Permission denied

Going to be running update for following packages:
 - obsidian-0.9.1

Press Enter key to continue...
Running update for:
Traceback (most recent call last):
  File "/nix/store/7y3h74xk58f5lwbqip8ns97wdpkjna3w-update.py", line 219, in <module>
    main(args.max_workers, args.keep_going, args.commit, args.packages)
  File "/nix/store/7y3h74xk58f5lwbqip8ns97wdpkjna3w-update.py", line 200, in main
    asyncio.run(start_updates(max_workers, keep_going, commit, packages))
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/nix/store/7y3h74xk58f5lwbqip8ns97wdpkjna3w-update.py", line 157, in start_updates
    nixpkgs_root_process = await check_subprocess('git', 'rev-parse', '--show-toplevel', stdout=asyncio.subprocess.PIPE)
  File "/nix/store/7y3h74xk58f5lwbqip8ns97wdpkjna3w-update.py", line 23, in check_subprocess
    process = await asyncio.create_subprocess_exec(*args, **kwargs)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```
That's the complete log. This was fixed in https://github.com/nix-community/infra/commit/4c898f7561d63975cb35d6f226ed92ca32972990
